version: "3.8"
services:
  container-application:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    depends_on:
      - application-one

  application-one:
    stdin_open: true
    build:
      context: ../application-one
      dockerfile: Dockerfile
    ports:
      - "8500:9000"
    volumes:
      - "/app/node_modules"
      - "./:/app"